; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Thu Mar 19 2020 21:32:43 GMT+0100 (Central European Standard Time)
M280 P0 S10 ; deploy BLTouch

