; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Thu Mar 19 2020 21:32:44 GMT+0100 (Central European Standard Time)
; Wait for set temperatures to be reached
M116 P0

